version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=marcketMobile'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=biel0alves0@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - "5050:80"
    depends_on:
      - postgres
