version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=marketMobile'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=admin'
    ports:
      - 5432:5432